### PR TITLE
UX redesign and automatically launch CIQ app

### PR DESCRIPTION
**Pull request by fm-sys**
Hi there, 

I really love your app, so I did some work on it. Hope you like it as well :)

- UX redesign
- Connect via the Garmin android SDK and automatically launch the gimporter CIQ app

Note: this does not change the method how data is transferred in general (like suggested in #7). Therefore, this change is 100% backwards compatible and doesn't require any changes at the CIQ app.

Tested on Android 10 (API 29) and Android 4.4 (API 19)

## Some screenshots
||||img|
-|-|-|-
||img|img|

### CODE REVIEW

**Comment by fm-sys** [comment]
Hi @haraldh,

May you take a look at these changes?

**Comment by haraldh** [comment]
@fm-sys , sorry, somehow this PR notification went unnoticed! Many thanks for your contribution. Will review and most likely merge the next days.

**Review by haraldh — CHANGES_REQUESTED** [review]
Would you mind removing the binary jars from git?

**Comment by fm-sys** [comment]
> Would you mind removing the binary jars from git?

I don't have a strong opinion about this, however it took me some time to figure out where to download the right files. Maybe we add links to the README instead?

**Comment by haraldh** [comment]
> > Would you mind removing the binary jars from git?
> 
> I don't have a strong opinion about this, however it took me some time to figure out where to download the right files. Maybe we add links to the README instead? 

make it so 😀

**Comment by fm-sys** [comment]
> > > Would you mind removing the binary jars from git?
> > 
> > 
> > I don't have a strong opinion about this, however it took me some time to figure out where to download the right files. Maybe we add links to the README instead?
> 
> make it so 😀

OK, done ;-)

**Comment by haraldh** [comment]
And now the last commit should be a fixup/squash with the first commit. Please rebase.

**Comment by haraldh** [comment]
and force push

**Comment by fm-sys** [comment]
Git challenge completed ;-)

**Comment by haraldh** [comment]
come on.. give me time..  I have family and a life 😀

**Comment by fm-sys** [comment]
Sure, no hurry. Take your time 👍

**Comment by haraldh** [comment]
Thank you very much! Due to Google wanting API Level >= 30, I had to add some Directory export button. Otherwise only file sharing would have worked.

**Comment by fm-sys** [comment]
> Thank you very much!

You're welcome! I am glad to be able to help :)

> I had to add some Directory export button. 

Thanks for adding this cool feature 👍

However, may I suggest some GUI cleanup? 

- The button looks quite nailed currently. Add some margin...
- While "Connectivity", "Settings" and "Files" are three different topics and justify their own card, I would suggest placing the directory export button inside the "Files" card

If you don't mind, I can open a small PR...

img

**Comment by fm-sys** [comment]
> Thank you very much!

You're welcome! I am glad to be able to help :)

> I had to add some Directory export button. 

Thanks for adding this cool feature 👍

However, may I suggest some GUI cleanup? 

- The button looks quite nailed currently. Add some margin...
- While "Connectivity", "Settings" and "Files" are three different topics and justify their own card, I would suggest placing the directory export button inside the "Files" card

If you don't mind, I can open a small PR...

img

**Pull request merged**
